# partly autogenerated, that's why it's so ugly!

# say 'make V=1' to see the full build output
ifndef V
Q = @
Q_LATEX = sh -c 'echo -e "   " `echo $$(basename "$$0") | tr a-z A-Z`"\t$${!\#/..\/..\//}"; ! "$$0" "$$@" | grep -A5 -E "^[^ ]+:[0-9]+:"'
Q_OTHER = sh -c 'echo -e "   " `echo $$(basename "$$0") | tr a-z A-Z`"\t$${!\#/..\/..\//}"; "$$0" "$$@" >/dev/null'
endif

LATEX = latex
PDFLATEX = pdflatex
BIBTEX = bibtex
DVIPS = dvips
DVIPDF = dvipdf
PDFTOEPS = pdftops -eps
PDFTOPS = pdf2ps
EPSTOPDF = epstopdf
FIGTODEV = fig2dev
MPOST = mpost

.PHONY: all clean archive

all:  summary

texfiles = $(wildcard *.tex)

.PHONY: summary
summary: summary.pdf

summary.pdf: $(texfiles) summary.bbl
	$(Q) rm -rf build/pdf/; mkdir -p build/pdf/
	$(Q) cd build/pdf/ && TEXINPUTS="../../:$$TEXINPUTS" $(Q_LATEX) $(PDFLATEX) -interaction=nonstopmode -file-line-error ../../summary.tex
	$(Q) cd build/pdf/ && TEXINPUTS="../../:$$TEXINPUTS" $(Q_LATEX) $(PDFLATEX) -interaction=nonstopmode -file-line-error ../../summary.tex
	$(Q) ln -f build/pdf/summary.pdf summary.pdf

summary.aux: $(texfiles)
	$(Q) $(Q_LATEX) $(LATEX) -interaction=nonstopmode -file-line-error summary.tex

summary.bbl: summary.aux
	$(Q)$(Q_OTHER) $(BIBTEX) summary

clean:
	rm -rf build/
	rm -f *.aux
	rm -f summary.dvi summary.idx summary.ind summary.ilg summary.out summary.toc summary.pdf summary.log

archive: summary-template.zip

summary-template.zip: *.tex Makefile ETHlogo.* refs.bib
	mkdir -p summary
	cp `git ls-files "*.tex" Makefile "ETHlogo.*" refs.bib` summary/
	perl -i -pe 's/\$$VERSION\$$/'"$$(git describe)/" summary/*.tex
	rm -f summary-template.zip
	zip -r summary-template.zip summary/
